"""Classification manuelle des 261 codes de data/reference/CAMEO.country.txt.

CAMEO.country.txt mélange trois natures d'entités sous un même référentiel
de codes à 3 lettres : des pays, des zones non nationales (continents,
régions géopolitiques, une ville) et des territoires dépendants ou à
souveraineté disputée. Distinction établie manuellement le 17 septembre
2026, décision de projet et non donnée téléchargée — c'est pourquoi ce
fichier vit dans src/ et pas dans data/.

entity_type prend trois valeurs :
- "pays"       : État souverain, y compris micro-États incontestés (ex.
                 Vatican City).
- "region"     : les 28 codes en tête du fichier source, avant la première
                 entrée alphabétique de pays (continents, régions
                 géopolitiques, plus Baghdad qui n'est pas un pays).
- "territoire" : dépendance administrative non contestée d'un autre État
                 (Bermuda, Hong Kong, Guadeloupe...) OU entité à
                 souveraineté disputée (voir note ci-dessous). Ces deux cas
                 sont fondus dans la même valeur par choix de projet : dans
                 les deux cas, l'objectif est de ne pas trancher un statut
                 politique dans une table de référence technique.

Cas à souveraineté disputée (PSE, TWN, ESH), annotés en commentaire en
regard de leur entrée : classés "territoire" par application de la même
règle générale, pas par une prise de position sur leur statut. Un
classement "pays" n'aurait pas été plus neutre.

Défaut connu du fichier source : le libellé de REU ("Runion") est déjà
sans accent dans CAMEO.country.txt (fichier ASCII, pas un artefact
d'encodage introduit ici) — recopié tel quel, non corrigé.

Ajout hors source : SSD (Soudan du Sud, indépendant depuis 2011) est
absent de CAMEO.country.txt — référentiel jamais mis à jour depuis.
Ajouté ici comme "pays" (voir commentaire en regard de l'entrée), pas
recopié du fichier d'origine.
"""

CAMEO_COUNTRY_TYPES: dict[str, tuple[str, str]] = {
    "WSB": ("West Bank", "region"),
    "BAG": ("Baghdad", "region"),
    "GZS": ("Gaza Strip", "region"),
    "AFR": ("Africa", "region"),
    "ASA": ("Asia", "region"),
    "BLK": ("Balkans", "region"),
    "CRB": ("Caribbean", "region"),
    "CAU": ("Caucasus", "region"),
    "CFR": ("Central Africa", "region"),
    "CAS": ("Central Asia", "region"),
    "CEU": ("Central Europe", "region"),
    "EIN": ("East Indies", "region"),
    "EAF": ("Eastern Africa", "region"),
    "EEU": ("Eastern Europe", "region"),
    "EUR": ("Europe", "region"),
    "LAM": ("Latin America", "region"),
    "MEA": ("Middle East", "region"),
    "MDT": ("Mediterranean", "region"),
    "NAF": ("North Africa", "region"),
    "NMR": ("North America", "region"),
    "PGS": ("Persian Gulf", "region"),
    "SCN": ("Scandinavia", "region"),
    "SAM": ("South America", "region"),
    "SAS": ("South Asia", "region"),
    "SEA": ("Southeast Asia", "region"),
    "SAF": ("Southern Africa", "region"),
    "WAF": ("West Africa", "region"),
    "WST": ("The West", "region"),
    "AFG": ("Afghanistan", "pays"),
    "ALA": ("Aland Islands", "territoire"),
    "ALB": ("Albania", "pays"),
    "DZA": ("Algeria", "pays"),
    "ASM": ("American Samoa", "territoire"),
    "AND": ("Andorra", "pays"),
    "AGO": ("Angola", "pays"),
    "AIA": ("Anguilla", "territoire"),
    "ATG": ("Antigua and Barbuda", "pays"),
    "ARG": ("Argentina", "pays"),
    "ARM": ("Armenia", "pays"),
    "ABW": ("Aruba", "territoire"),
    "AUS": ("Australia", "pays"),
    "AUT": ("Austria", "pays"),
    "AZE": ("Azerbaijan", "pays"),
    "BHS": ("Bahamas", "pays"),
    "BHR": ("Bahrain", "pays"),
    "BGD": ("Bangladesh", "pays"),
    "BRB": ("Barbados", "pays"),
    "BLR": ("Belarus", "pays"),
    "BEL": ("Belgium", "pays"),
    "BLZ": ("Belize", "pays"),
    "BEN": ("Benin", "pays"),
    "BMU": ("Bermuda", "territoire"),
    "BTN": ("Bhutan", "pays"),
    "BOL": ("Bolivia", "pays"),
    "BIH": ("Bosnia and Herzegovina", "pays"),
    "BWA": ("Botswana", "pays"),
    "BRA": ("Brazil", "pays"),
    "VGB": ("British Virgin Islands", "territoire"),
    "BRN": ("Brunei Darussalam", "pays"),
    "BGR": ("Bulgaria", "pays"),
    "BFA": ("Burkina Faso", "pays"),
    "BDI": ("Burundi", "pays"),
    "KHM": ("Cambodia", "pays"),
    "CMR": ("Cameroon", "pays"),
    "CAN": ("Canada", "pays"),
    "CPV": ("Cape Verde", "pays"),
    "CYM": ("Cayman Islands", "territoire"),
    "CAF": ("Central African Republic", "pays"),
    "TCD": ("Chad", "pays"),
    "CHL": ("Chile", "pays"),
    "CHN": ("China", "pays"),
    "COL": ("Columbia", "pays"),
    "COM": ("Comoros", "pays"),
    "COD": ("Democratic Republic of the Congo", "pays"),
    "COG": ("People's Republic of the Congo", "pays"),
    "COK": ("Cook Islands", "territoire"),
    "CRI": ("Costa Rica", "pays"),
    "CIV": ("Ivory Coast", "pays"),
    "HRV": ("Croatia", "pays"),
    "CUB": ("Cuba", "pays"),
    "CYP": ("Cyprus", "pays"),
    "CZE": ("Czech Republic", "pays"),
    "DNK": ("Denmark", "pays"),
    "DJI": ("Djibouti", "pays"),
    "DMA": ("Dominica", "pays"),
    "DOM": ("Dominican Republic", "pays"),
    "TMP": ("East Timor", "pays"),
    "ECU": ("Ecuador", "pays"),
    "EGY": ("Egypt", "pays"),
    "SLV": ("El Salvador", "pays"),
    "GNQ": ("Equatorial Guinea", "pays"),
    "ERI": ("Eritrea", "pays"),
    "EST": ("Estonia", "pays"),
    "ETH": ("Ethiopia", "pays"),
    "FRO": ("Faeroe Islands", "territoire"),
    "FLK": ("Falkland Islands", "territoire"),
    "FJI": ("Fiji", "pays"),
    "FIN": ("Finland", "pays"),
    "FRA": ("France", "pays"),
    "GUF": ("French Guiana", "territoire"),
    "PYF": ("French Polynesia", "territoire"),
    "GAB": ("Gabon", "pays"),
    "GMB": ("Gambia", "pays"),
    "GEO": ("Georgia", "pays"),
    "DEU": ("Germany", "pays"),
    "GHA": ("Ghana", "pays"),
    "GIB": ("Gibraltar", "territoire"),
    "GRC": ("Greece", "pays"),
    "GRL": ("Greenland", "territoire"),
    "GRD": ("Grenada", "pays"),
    "GLP": ("Guadeloupe", "territoire"),
    "GUM": ("Guam", "territoire"),
    "GTM": ("Guatemala", "pays"),
    "GIN": ("Guinea", "pays"),
    "GNB": ("Guinea-Bissau", "pays"),
    "GUY": ("Guyana", "pays"),
    "HTI": ("Haiti", "pays"),
    "VAT": ("Vatican City", "pays"),
    "HND": ("Honduras", "pays"),
    "HKG": ("Hong Kong", "territoire"),
    "HUN": ("Hungary", "pays"),
    "ISL": ("Iceland", "pays"),
    "IND": ("India", "pays"),
    "IDN": ("Indonesia", "pays"),
    "IRN": ("Iran", "pays"),
    "IRQ": ("Iraq", "pays"),
    "IRL": ("Ireland", "pays"),
    "IMY": ("Isle of Man", "territoire"),
    "ISR": ("Israel", "pays"),
    "ITA": ("Italy", "pays"),
    "JAM": ("Jamaica", "pays"),
    "JPN": ("Japan", "pays"),
    "JOR": ("Jordan", "pays"),
    "KAZ": ("Kazakhstan", "pays"),
    "KEN": ("Kenya", "pays"),
    "KIR": ("Kiribati", "pays"),
    "PRK": ("North Korea", "pays"),
    "KOR": ("South Korea", "pays"),
    "KWT": ("Kuwait", "pays"),
    "KGZ": ("Kyrgyzstan", "pays"),
    "LAO": ("Laos", "pays"),
    "LVA": ("Latvia", "pays"),
    "LBN": ("Lebanon", "pays"),
    "LSO": ("Lesotho", "pays"),
    "LBR": ("Liberia", "pays"),
    "LBY": ("Libya", "pays"),
    "LIE": ("Liechtenstein", "pays"),
    "LTU": ("Lithuania", "pays"),
    "LUX": ("Luxembourg", "pays"),
    "MAC": ("Macao", "territoire"),
    "MKD": ("Macedonia", "pays"),
    "MDG": ("Madagascar", "pays"),
    "MWI": ("Malawi", "pays"),
    "MYS": ("Malaysia", "pays"),
    "MDV": ("Maldives", "pays"),
    "MLI": ("Mali", "pays"),
    "MLT": ("Malta", "pays"),
    "MHL": ("Marshall Islands", "pays"),
    "MTQ": ("Martinique", "territoire"),
    "MRT": ("Mauritania", "pays"),
    "MUS": ("Mauritius", "pays"),
    "MYT": ("Mayotte", "territoire"),
    "MEX": ("Mexico", "pays"),
    "FSM": ("Micronesia", "pays"),
    "MDA": ("Moldova", "pays"),
    "MCO": ("Monaco", "pays"),
    "MNG": ("Mongolia", "pays"),
    "MTN": ("Montenegro", "pays"),
    "MSR": ("Montserrat", "territoire"),
    "MAR": ("Morocco", "pays"),
    "MOZ": ("Mozambique", "pays"),
    "MMR": ("Myanmar", "pays"),
    "NAM": ("Namibia", "pays"),
    "NRU": ("Nauru", "pays"),
    "NPL": ("Nepal", "pays"),
    "NLD": ("Netherlands", "pays"),
    "ANT": ("Netherlands Antilles", "territoire"),
    "NCL": ("New Caledonia", "territoire"),
    "NZL": ("New Zealand", "pays"),
    "NIC": ("Nicaragua", "pays"),
    "NER": ("Niger", "pays"),
    "NGA": ("Nigeria", "pays"),
    "NIU": ("Niue", "territoire"),
    "NFK": ("Norfolk Island", "territoire"),
    "MNP": ("Northern Mariana Islands", "territoire"),
    "NOR": ("Norway", "pays"),
    "PSE": ("Occupied Palestinian Territory", "territoire"),  # souveraineté disputée -> territoire par la règle générale, pas une prise de position
    "OMN": ("Oman", "pays"),
    "PAK": ("Pakistan", "pays"),
    "PLW": ("Palau", "pays"),
    "PAN": ("Panama", "pays"),
    "PNG": ("Papua New Guinea", "pays"),
    "PRY": ("Paraguay", "pays"),
    "PER": ("Peru", "pays"),
    "PHL": ("Philippines", "pays"),
    "PCN": ("Pitcairn", "territoire"),
    "POL": ("Poland", "pays"),
    "PRT": ("Portugal", "pays"),
    "PRI": ("Puerto Rico", "territoire"),
    "QAT": ("Qatar", "pays"),
    "REU": ("Runion", "territoire"),
    "ROM": ("Romania", "pays"),
    "RUS": ("Russia", "pays"),
    "RWA": ("Rwanda", "pays"),
    "SHN": ("Saint Helena", "territoire"),
    "KNA": ("Saint Kitts-Nevis", "pays"),
    "LCA": ("Saint Lucia", "pays"),
    "SPM": ("Saint Pierre and Miquelon", "territoire"),
    "VCT": ("Saint Vincent and the Grenadines", "pays"),
    "WSM": ("Samoa", "pays"),
    "SMR": ("San Marino", "pays"),
    "STP": ("Sao Tome and Principe", "pays"),
    "SAU": ("Saudi Arabia", "pays"),
    "SEN": ("Senegal", "pays"),
    "SRB": ("Serbia", "pays"),
    "SYC": ("Seychelles", "pays"),
    "SLE": ("Sierra Leone", "pays"),
    "SGP": ("Singapore", "pays"),
    "SVK": ("Slovakia", "pays"),
    "SVN": ("Slovenia", "pays"),
    "SLB": ("Solomon Islands", "pays"),
    "SOM": ("Somalia", "pays"),
    "ZAF": ("South Africa", "pays"),
    "SSD": ("South Sudan", "pays"),  # absent de CAMEO.country.txt (independant depuis 2011), ajoute par nous
    "ESP": ("Spain", "pays"),
    "LKA": ("Sri Lanka", "pays"),
    "SDN": ("Sudan", "pays"),
    "SUR": ("Suriname", "pays"),
    "SJM": ("Svalbard and Jan Mayen Islands", "territoire"),
    "SWZ": ("Swaziland", "pays"),
    "SWE": ("Sweden", "pays"),
    "CHE": ("Switzerland", "pays"),
    "SYR": ("Syria", "pays"),
    "TWN": ("Taiwan", "territoire"),  # souveraineté disputée -> territoire par la règle générale, pas une prise de position
    "TJK": ("Tajikistan", "pays"),
    "TZA": ("Tanzania", "pays"),
    "THA": ("Thailand", "pays"),
    "TGO": ("Togo", "pays"),
    "TKL": ("Tokelau", "territoire"),
    "TON": ("Tonga", "pays"),
    "TTO": ("Trinidad and Tobago", "pays"),
    "TUN": ("Tunisia", "pays"),
    "TUR": ("Turkey", "pays"),
    "TKM": ("Turkmenistan", "pays"),
    "TCA": ("Turks and Caicos Islands", "territoire"),
    "TUV": ("Tuvalu", "pays"),
    "UGA": ("Uganda", "pays"),
    "UKR": ("Ukraine", "pays"),
    "ARE": ("United Arab Emirates", "pays"),
    "GBR": ("United Kingdom", "pays"),
    "USA": ("United States", "pays"),
    "VIR": ("United States Virgin Islands", "territoire"),
    "URY": ("Uruguay", "pays"),
    "UZB": ("Uzbekistan", "pays"),
    "VUT": ("Vanuatu", "pays"),
    "VEN": ("Venezuela", "pays"),
    "VNM": ("Vietnam", "pays"),
    "WLF": ("Wallis and Futuna Islands", "territoire"),
    "ESH": ("Western Sahara", "territoire"),  # souveraineté disputée -> territoire par la règle générale, pas une prise de position
    "YEM": ("Yemen", "pays"),
    "ZMB": ("Zambia", "pays"),
    "ZWE": ("Zimbabwe", "pays"),
}
